// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2t3KpSl0X--Ce9ANKWnf_qPsEzhb8oys',
    appId: '1:383976062219:web:569fa7eb4875fe7dd8760e',
    messagingSenderId: '383976062219',
    projectId: 'teegram-75a77',
    authDomain: 'teegram-75a77.firebaseapp.com',
    storageBucket: 'teegram-75a77.appspot.com',
    measurementId: 'G-S1SKSV4FYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKu9Oh-eqB57Hl4vvyAeAElNEydkVdwXY',
    appId: '1:383976062219:android:f9f14f95e6c97d8dd8760e',
    messagingSenderId: '383976062219',
    projectId: 'teegram-75a77',
    storageBucket: 'teegram-75a77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmyVPfKJhSJmwwqmSEE69k79-L7QEy1Mw',
    appId: '1:383976062219:ios:70ce1a321a5836c4d8760e',
    messagingSenderId: '383976062219',
    projectId: 'teegram-75a77',
    storageBucket: 'teegram-75a77.appspot.com',
    iosBundleId: 'com.example.teegram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmyVPfKJhSJmwwqmSEE69k79-L7QEy1Mw',
    appId: '1:383976062219:ios:70ce1a321a5836c4d8760e',
    messagingSenderId: '383976062219',
    projectId: 'teegram-75a77',
    storageBucket: 'teegram-75a77.appspot.com',
    iosBundleId: 'com.example.teegram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2t3KpSl0X--Ce9ANKWnf_qPsEzhb8oys',
    appId: '1:383976062219:web:535acc1670b6054ed8760e',
    messagingSenderId: '383976062219',
    projectId: 'teegram-75a77',
    authDomain: 'teegram-75a77.firebaseapp.com',
    storageBucket: 'teegram-75a77.appspot.com',
    measurementId: 'G-2PSWPXZ2N9',
  );
}
